name: nhac_uong_thuoc
description: "Ứng dụng nhắc uống thuốc hằng ngày."
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^22.3.1
  flutter_timezone: ^5.0.1
  timezone: ^0.11.0
  shared_preferences: ^2.5.5
  image_picker: ^1.1.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
